version: '3'

services:
  portfolio:
    image: paulboiseau/portfolio
    build:
        context: .
        dockerfile: docker/Dockerfile
    container_name: portfolio
    networks:
      - websites
    ports:
        - 8181:80
    environment:
        - NGINX_HOST=paulboiseau.com

networks:
  websites:
    driver: bridge
